name: UAParser.js CI-Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, ppc64le]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 'lts/*'
      - name: Run the test
        run: |
          npm ci
          npx playwright install --with-deps
          npm test
